sudo: required
services:
  - docker

before_install:
  - docker build -t rajeshbalan78/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajeshbalan78/react-test npm test

after_success:
  - docker build -t balanrajesh/multi-client ./client
  - docker build -t balanrajesh/multi-nginx ./nginx
  - docker build -t balanrajesh/multi-server ./server
  - docker build -t balanrajesh/multi-worker ./worker

  # Login to Docker Hub, the variables are defined in Travis CI
  
  # - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 
  # push the production images to docker hub

  - docker push balanrajesh/multi-client
  - docker push balanrajesh/multi-nginx
  - docker push balanrajesh/multi-server
  - docker push balanrajesh/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: ap-south-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket-name: elasticbeanstalk-ap-south-1-372198002688
#  bucker-path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: "$AWS_SECRET_KEY"

